# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'Pipeline agents'

steps:
- task: octane-start-task@2
  inputs:
    OctaneServiceConnection: 'MyHmv01735'
    WorkspaceList: '1002'
    GithubRepositoryConnection: 'github connection 1'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    options: '-fn'
- task: octane-end-task@2
  inputs:
    OctaneServiceConnection: 'MyHmv01735'
    WorkspaceList: '1002'
    GithubRepositoryConnection: 'github connection 1'
